AllCops:
  # DisplayCopNames: true  ---- enable for debugging rubocop
  TargetRubyVersion: 3.0

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max:  120
  
Metrics/BlockLength:
  Enabled: false
